# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maxent_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.real_freq_frame = QtWidgets.QFrame(self.centralwidget)
        self.real_freq_frame.setGeometry(QtCore.QRect(10, 10, 171, 141))
        self.real_freq_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.real_freq_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.real_freq_frame.setObjectName("real_freq_frame")
        self.label = QtWidgets.QLabel(self.real_freq_frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 17))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.real_freq_frame)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 31, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.real_freq_frame)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 21, 17))
        self.label_4.setObjectName("label_4")
        self.grid_type_combo = QtWidgets.QComboBox(self.real_freq_frame)
        self.grid_type_combo.setGeometry(QtCore.QRect(10, 40, 141, 25))
        self.grid_type_combo.setObjectName("grid_type_combo")
        self.grid_type_combo.addItem("")
        self.grid_type_combo.addItem("")
        self.max_real_freq = QtWidgets.QLineEdit(self.real_freq_frame)
        self.max_real_freq.setGeometry(QtCore.QRect(40, 70, 41, 25))
        self.max_real_freq.setObjectName("max_real_freq")
        self.num_real_freq = QtWidgets.QLineEdit(self.real_freq_frame)
        self.num_real_freq.setGeometry(QtCore.QRect(40, 110, 41, 25))
        self.num_real_freq.setObjectName("num_real_freq")
        self.gen_real_grid_button = QtWidgets.QPushButton(self.real_freq_frame)
        self.gen_real_grid_button.setGeometry(QtCore.QRect(90, 110, 71, 25))
        self.gen_real_grid_button.setObjectName("gen_real_grid_button")
        self.input_data_frame = QtWidgets.QFrame(self.centralwidget)
        self.input_data_frame.setGeometry(QtCore.QRect(200, 10, 561, 141))
        self.input_data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_data_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_data_frame.setObjectName("input_data_frame")
        self.label_2 = QtWidgets.QLabel(self.input_data_frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 161, 17))
        self.label_2.setObjectName("label_2")
        self.inp_data_type = QtWidgets.QComboBox(self.input_data_frame)
        self.inp_data_type.setGeometry(QtCore.QRect(180, 10, 121, 25))
        self.inp_data_type.setObjectName("inp_data_type")
        self.inp_data_type.addItem("")
        self.inp_data_type.addItem("")
        self.label_5 = QtWidgets.QLabel(self.input_data_frame)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label_5.setObjectName("label_5")
        self.inp_file_name = QtWidgets.QLineEdit(self.input_data_frame)
        self.inp_file_name.setGeometry(QtCore.QRect(80, 40, 461, 25))
        self.inp_file_name.setObjectName("inp_file_name")
        self.label_6 = QtWidgets.QLabel(self.input_data_frame)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_6.setObjectName("label_6")
        self.iteration_type_combo = QtWidgets.QComboBox(self.input_data_frame)
        self.iteration_type_combo.setGeometry(QtCore.QRect(80, 70, 86, 25))
        self.iteration_type_combo.setObjectName("iteration_type_combo")
        self.iteration_type_combo.addItem("")
        self.iteration_type_combo.addItem("")
        self.iteration_type_combo.addItem("")
        self.iteration_number = QtWidgets.QLineEdit(self.input_data_frame)
        self.iteration_number.setGeometry(QtCore.QRect(170, 70, 31, 25))
        self.iteration_number.setObjectName("iteration_number")
        self.label_7 = QtWidgets.QLabel(self.input_data_frame)
        self.label_7.setGeometry(QtCore.QRect(230, 70, 41, 17))
        self.label_7.setObjectName("label_7")
        self.atom_number = QtWidgets.QLineEdit(self.input_data_frame)
        self.atom_number.setGeometry(QtCore.QRect(280, 70, 21, 25))
        self.atom_number.setObjectName("atom_number")
        self.label_8 = QtWidgets.QLabel(self.input_data_frame)
        self.label_8.setGeometry(QtCore.QRect(320, 70, 51, 17))
        self.label_8.setObjectName("label_8")
        self.orbital_number = QtWidgets.QLineEdit(self.input_data_frame)
        self.orbital_number.setGeometry(QtCore.QRect(380, 70, 21, 25))
        self.orbital_number.setObjectName("orbital_number")
        self.label_9 = QtWidgets.QLabel(self.input_data_frame)
        self.label_9.setGeometry(QtCore.QRect(420, 70, 31, 17))
        self.label_9.setObjectName("label_9")
        self.spin_type_combo = QtWidgets.QComboBox(self.input_data_frame)
        self.spin_type_combo.setGeometry(QtCore.QRect(460, 70, 81, 25))
        self.spin_type_combo.setObjectName("spin_type_combo")
        self.spin_type_combo.addItem("")
        self.spin_type_combo.addItem("")
        self.spin_type_combo.addItem("")
        self.load_data_button = QtWidgets.QPushButton(self.input_data_frame)
        self.load_data_button.setGeometry(QtCore.QRect(450, 110, 89, 25))
        self.load_data_button.setObjectName("load_data_button")
        self.label_10 = QtWidgets.QLabel(self.input_data_frame)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 241, 17))
        self.label_10.setObjectName("label_10")
        self.num_mats_freq = QtWidgets.QLineEdit(self.input_data_frame)
        self.num_mats_freq.setGeometry(QtCore.QRect(250, 110, 41, 25))
        self.num_mats_freq.setObjectName("num_mats_freq")
        self.continuation_frame = QtWidgets.QFrame(self.centralwidget)
        self.continuation_frame.setGeometry(QtCore.QRect(10, 170, 751, 381))
        self.continuation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.continuation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.continuation_frame.setObjectName("continuation_frame")
        self.doit_button = QtWidgets.QPushButton(self.continuation_frame)
        self.doit_button.setGeometry(QtCore.QRect(650, 350, 89, 25))
        self.doit_button.setObjectName("doit_button")
        self.preblur_button = QtWidgets.QRadioButton(self.continuation_frame)
        self.preblur_button.setGeometry(QtCore.QRect(10, 10, 71, 23))
        self.preblur_button.setObjectName("preblur_button")
        self.blur_width = QtWidgets.QLineEdit(self.continuation_frame)
        self.blur_width.setGeometry(QtCore.QRect(80, 40, 113, 25))
        self.blur_width.setObjectName("blur_width")
        self.label_11 = QtWidgets.QLabel(self.continuation_frame)
        self.label_11.setGeometry(QtCore.QRect(30, 40, 51, 17))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.real_freq_frame.setToolTip(_translate("MainWindow", "configure real-frequency grid"))
        self.real_freq_frame.setWhatsThis(_translate("MainWindow", "real-frequency grid"))
        self.label.setText(_translate("MainWindow", "Real-frequency grid"))
        self.label_3.setText(_translate("MainWindow", "max"))
        self.label_4.setText(_translate("MainWindow", "n"))
        self.grid_type_combo.setToolTip(_translate("MainWindow", "equispaced or centered grid (denser around Fermi energy)"))
        self.grid_type_combo.setItemText(0, _translate("MainWindow", "equispaced grid"))
        self.grid_type_combo.setItemText(1, _translate("MainWindow", "centered grid"))
        self.max_real_freq.setToolTip(_translate("MainWindow", "upper border of real-frequency grid. (lower border is set symmetrically)"))
        self.max_real_freq.setText(_translate("MainWindow", "10"))
        self.num_real_freq.setToolTip(_translate("MainWindow", "number frequencies on real axis; should be an odd number"))
        self.num_real_freq.setText(_translate("MainWindow", "401"))
        self.gen_real_grid_button.setText(_translate("MainWindow", "Generate"))
        self.label_2.setText(_translate("MainWindow", "Load w2dynamics data"))
        self.inp_data_type.setItemText(0, _translate("MainWindow", "Self-energy"))
        self.inp_data_type.setItemText(1, _translate("MainWindow", "Green\'s function"))
        self.label_5.setText(_translate("MainWindow", "file name"))
        self.inp_file_name.setToolTip(_translate("MainWindow", "file path and name of a w2dynamics output file"))
        self.label_6.setText(_translate("MainWindow", "iteration"))
        self.iteration_type_combo.setItemText(0, _translate("MainWindow", "DMFT"))
        self.iteration_type_combo.setItemText(1, _translate("MainWindow", "STAT"))
        self.iteration_type_combo.setItemText(2, _translate("MainWindow", "WORM"))
        self.iteration_number.setToolTip(_translate("MainWindow", "integer; leave empty for last iteration"))
        self.label_7.setText(_translate("MainWindow", "Atom"))
        self.atom_number.setToolTip(_translate("MainWindow", "choose inequivalent atom (one-based integer)"))
        self.atom_number.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "Orbital"))
        self.orbital_number.setToolTip(_translate("MainWindow", "choose orbital (one-based integer)"))
        self.orbital_number.setText(_translate("MainWindow", "1"))
        self.label_9.setText(_translate("MainWindow", "Spin"))
        self.spin_type_combo.setToolTip(_translate("MainWindow", "choose spin up/down; average for paramagnetic system"))
        self.spin_type_combo.setItemText(0, _translate("MainWindow", "average"))
        self.spin_type_combo.setItemText(1, _translate("MainWindow", "up"))
        self.spin_type_combo.setItemText(2, _translate("MainWindow", "down"))
        self.load_data_button.setText(_translate("MainWindow", "Load data"))
        self.label_10.setText(_translate("MainWindow", "Number of Matsubara frequencies"))
        self.num_mats_freq.setToolTip(_translate("MainWindow", "How many Matsubara frequencies do you want to use for the continuation?"))
        self.doit_button.setText(_translate("MainWindow", "Do it!"))
        self.preblur_button.setText(_translate("MainWindow", "Preblur"))
        self.blur_width.setText(_translate("MainWindow", "0.1"))
        self.label_11.setText(_translate("MainWindow", "Width"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

