name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - name: Install Python 3
            uses: actions/setup-python@v1
            with:
              python-version: 3.12
          - name: Install dependencies
            run: |
              python3 -m venv .venv
              source .venv/bin/activate
              .venv/bin/python -m pip install --upgrade pip
              .venv/bin/python -m pip install -e .
              .venv/bin/python -m pip install jupyter nbclient
          - name: Run tests
            run: .venv/bin/python -m unittest tests/ana_cont_tests.py -v
          - name: Run tests (pytest)
            run: .venv/bin/python -m pytest tests/
